version: '2'
services:
  zookeeper-server1:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-server2:2888:3888,zookeeper-server3:2888:3888
  zookeeper-server2:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper-server1:2888:3888,0.0.0.0:2888:3888,zookeeper-server3:2888:3888
  zookeeper-server3:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper-server1:2888:3888,zookeeper-server2:2888:3888,0.0.0.0:2888:3888
  kafka1:
    image: 'wurstmeister/kafka'
    ports:
      - 29092:9092
    environment:
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server1:2181,zookeeper-server2:2181,zookeeper-server3:2181
      - KAFKA_ADVERTISED_HOST_NAME=${HOST_IP}
      - KAFKA_ADVERTISED_PORT=29092
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
  kafka2:
    image: 'wurstmeister/kafka'
    ports:
      - 29093:9092
    environment:
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server1:2181,zookeeper-server2:2181,zookeeper-server3:2181
      - KAFKA_ADVERTISED_HOST_NAME=${HOST_IP}
      - KAFKA_ADVERTISED_PORT=29093
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
  kafka3:
    image: 'wurstmeister/kafka'
    ports:
      - 29094:9092
    environment:
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server1:2181,zookeeper-server2:2181,zookeeper-server3:2181
      - KAFKA_ADVERTISED_HOST_NAME=${HOST_IP}
      - KAFKA_ADVERTISED_PORT=29094
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
