version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server1:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVERS=zookeeper-server1:12181:13181;zookeeper-server2:22888:23888;zookeeper-server3:32888:33888
  zookeeper-server2:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - 2888:2888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_CLIENT_PORT=2888
      - ZOOKEEPER_SERVERS=zookeeper-server1:12181:13181;zookeeper-server2:22888:23888;zookeeper-server3:32888:33888
  zookeeper-server3:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - 3888:3888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=3
      - ZOOKEEPER_CLIENT_PORT=3888
      - ZOOKEEPER_SERVERS=zookeeper-server1:12181:13181;zookeeper-server2:22888:23888;zookeeper-server3:32888:33888
  kafka1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server1:2181,zookeeper-server2:2888,zookeeper-server3:3888
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092, PLAINTEXT_HOST://localhost:29092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
  kafka2:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server1:2181,zookeeper-server2:2888,zookeeper-server3:3888
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093,PLAINTEXT_HOST://:29093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9093, PLAINTEXT_HOST://localhost:29093
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
  kafka3:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - 9094:9094
      - 29094:29094
    environment:
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server1:2181,zookeeper-server2:2888,zookeeper-server3:3888
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,PLAINTEXT_HOST://:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9094, PLAINTEXT_HOST://localhost:29094
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server1
      - zookeeper-server2
      - zookeeper-server3
